name: Terraform AWS CI/CD

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0 # Set the desired Terraform version

    - name: Create AWS credentials file
      run: |
        mkdir -p ~/.aws
        echo "[default]" > ~/.aws/credentials
        echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
        echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
        chmod 600 ~/.aws/credentials

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.AWS_PRIVATE_KEYY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Initialize Terraform
      run: terraform init
    
    - name: Refresh Terraform State
      run: terraform refresh

    - name: Plan
      run: terraform plan

    - name: Apply
      run: terraform apply -auto-approve

    # - name: Clean up
    #   run: terraform destroy -auto-approve